version: "3.7"

services:
  rng-api:
    image: labs/rng-api:21.05
    configs:
      - source: rng-logging
        target: /app/config/logging.json
    secrets:
      - source: rng-api
        target: /app/config/override.json
    ports:
      - "8089:80"
    networks:
      - app-net

  rng-web:
    image: labs/rng-web:21.05
    configs:
      - source: rng-logging
        target: /app/config/logging.json
    secrets:
      - source: rng-web
        target: /app/config/override.json
    ports:
      - "8090:80"
    networks:
      - app-net

networks:
  app-net:

configs:
  rng-logging:
    external: true

secrets:
  rng-api:
    external: true

  rng-web:
    external: true
